version: '3'
services:
  mysql-server:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: user
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  flask_app:
    image: sarsh/flask-application:v2_without_db
    container_name: flask-app-container
    ports:
      - "5000:5000"
    depends_on:
      - mysql-server
    environment:
      MYSQL_HOST: mysql-server
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root123456
      MYSQL_DATABASE: user
      FLASK_APP: homepage.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_DEBUG: true